# Generated by Django 5.1 on 2024-12-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0002_alter_cliente_correo_alter_cliente_fecha_nac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
