# Generated by Django 5.1 on 2024-12-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provedores_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedor',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='id_provedor',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provedor',
            name='tipo_de_producto',
            field=models.CharField(max_length=50),
        ),
    ]
