# Generated by Django 5.1 on 2024-12-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numsegurosocial',
            field=models.CharField(max_length=9),
        ),
    ]
